import puppeteer from 'puppeteer-core';
import fs from 'node:fs';
const ids = process.argv.slice(2);
const b = await puppeteer.launch({ executablePath: 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: 'new', args: ['--allow-file-access-from-files'] });
const p = await b.newPage(); await p.setViewport({ width: 1600, height: 1200 });
const html = '<body style="margin:0;background:#000;display:flex;flex-wrap:wrap">' + ids.map(i => `<div style="width:400px;color:#fff;font:14px sans-serif"><img src="file:///C:/Users/kkm/Desktop/Claude Code/race3d/web/assets/tex/${i}/diff.jpg" width=400 height=380>${i}</div>`).join('');
const f = process.cwd() + '/tests/shots/_sheet.html';
fs.writeFileSync(f, html);
await p.goto('file:///' + f.split('\\').join('/')); await new Promise(r => setTimeout(r, 1500));
await p.screenshot({ path: 'tests/shots/sheet.png' }); await b.close();
