import puppeteer from 'puppeteer-core';
const b = await puppeteer.launch({ executablePath: 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: 'new', args: ['--enable-gpu', '--use-angle=d3d11', '--window-size=1280,720'], defaultViewport: { width: 1280, height: 720 } });
const p = await b.newPage();
await p.goto('http://127.0.0.1:8790/index.html?solo=1&track=circuit&bots=0&q=high&bot=1', { waitUntil: 'load' });
await new Promise(r => setTimeout(r, 30000));
const r = await p.evaluate(async () => {
  const THREE = await import('/vendor/three/three.module.js');
  const v = window.__game.view, g = window.__gfx;
  v.updateCamera = function () { const mm = this.cars[0].mesh, cam = this.gfx.camera; cam.position.set(mm.position.x + 4, mm.position.y + 22, mm.position.z + 2); cam.lookAt(mm.position); cam.fov = 50; cam.updateProjectionMatrix(); };
  const m = v.cars[0].mesh;
  const box = new THREE.Mesh(new THREE.BoxGeometry(1, 1, 1), new THREE.MeshStandardMaterial({ color: 0x00ff00 }));
  box.position.set(3, 1, 0); box.castShadow = true; m.add(box);
  const box2 = new THREE.Mesh(new THREE.BoxGeometry(1, 1, 1), new THREE.MeshStandardMaterial({ color: 0x0000ff }));
  box2.position.copy(m.position).add(new THREE.Vector3(-3, 1, 0)); box2.castShadow = true; g.scene.add(box2);
  return { same: box.material.constructor === THREE.MeshStandardMaterial, carParent: m.parent === g.scene, sceneKids: g.scene.children.length };
});
console.log(JSON.stringify(r));
await new Promise(r => setTimeout(r, 1500));
await p.screenshot({ path: 'tests/shots/shadow_box_far.png' });
await b.close();
